language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
services:
  - redis-server
cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
- cargo clean
- cargo build
- cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
